services:
  db:
    image:  mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=jesse
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=vdb
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
  web:
    image:  trafex/php-nginx
    volumes:
      - ./www:/var/www/html
    links:
      - db
    ports:
      - "80:8080"
  pma:
    image: phpmyadmin
    ports:
      - "8080:80"
    links:
      - db
